import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
   "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
dynamic_title = false

[font]
normal = { family = "MonaspiceRn Nerd Font", style = "Light" }
bold = { family = "MonaspiceRn Nerd Font", style = "Bold" }
italic = { family = "MonaspiceRn Nerd Font", style = "LightItalic" }
bold_italic = { family = "MonaspiceRn Nerd Font", style = "BoldItalic" }
size = 12