
[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
dynamic_title = false

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "LightItalic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "BoldItalic" }
size = 12

[general]
import = [
   "~/.config/alacritty/catppuccin-latte.toml"
]
